[[entries]]
template = "fzf"
target = "~/.config/fish/fzf-colors.fish"
command = "fish ~/.config/fish/fzf-colors.fish"

[[entries]]
template = "obsidian"
target = "~/Notes/.obsidian/snippets/whiskers.css"

# Thèse
[[entries]]
template = "obsidian"
target = "~/Thèse/.obsidian/snippets/whiskers.css"

[[entries]]
template = "lua"
target = "~/.local/share/nvim/lazy/catppuccin/lua/catppuccin/palettes/dynamic.lua"

[[entries]]
template = "bat"
target = "~/.config/bat/themes/whiskers.tmTheme"
command = "bat cache --build"

[[entries]]
template = "kitty"
target = "~/.config/kitty/themes/whiskers.conf"
command = "kitten themes --reload-in=all Whiskers; pkill -SIGUSR1 kitty"

[[entries]]
template = "helix"
target = "~/.config/helix/themes/whiskers.toml"
variant = "default"

[[entries]]
template = "zathura"
target = "~/.config/zathura/colors.conf"

[[entries]]
template = "gtk"
target = "~/.config/gtk-4.0/gtk.css"

[[entries]]
template = "gtk"
target = "~/.config/gtk-3.0/gtk.css"

[[entries]]
template = "toml"
target = "~/.mozilla/colors.toml"

[[entries]]
template = "niri"
target = "~/.config/niri/colors.kdl"

[[entries]]
template = "minilauncher"
target = "~/.config/minilauncher/colors.toml"
